name: Build & Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        environment:
            name: demo
            url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - uses: mymindstorm/setup-emsdk@v14
            - name: Verify
              run: emcc -v
            - name: Install Dependencies
              run: pip install -r src/wasm/requirements.txt
            - name: Vite Github Pages Deployer
              uses: skywarth/vite-github-pages-deployer@v1.5.0
              id: deploy_to_pages
